name: CI/CD Pipeline

on:
  push:
    branches:
      - 'develop'
      - 'main'
  pull_request:
    branches:
      - 'develop'
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'adopt'
          java-version: '17'
    
      - name: Make gradlew executable
        run: chmod +x gradlew
        working-directory: Software
  
      - name: Build with Gradle
        run: ./gradlew build
        working-directory: Software

      - name: Run Unit Tests
        run: ./gradlew test
        working-directory: Software
